class ApplicationError(Exception): ...


class AuthenticationError(ApplicationError): ...


class AlreadyAuthenticatedError(AuthenticationError): ...


class AuthorizationError(ApplicationError): ...


class UserAlreadyExistsError(ApplicationError): ...


class EmailNotVerifiedError(AuthenticationError): ...


class InvalidEmailVerificationTokenError(ApplicationError): ...


class ExpiredEmailVerificationTokenError(ApplicationError): ...
